from __future__ import annotations

import csv
import hashlib
import json
import math
import os
import shutil
from collections import Counter, defaultdict
from dataclasses import asdict, dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import numpy as np
from PIL import Image, ImageOps

from . import TASKS
from .dataset import FrameExample, read_manifest
from .metrics import (
    binary_metrics,
    select_abstention_thresholds,
    select_threshold,
    selective_binary_metrics,
)

YOLO_DATASET_MARKER = ".baby-monitor-yolo-dataset"
YOLO_ARTIFACT_MARKER = ".baby-monitor-yolo-artifacts"
POSE_DETAIL_STRATEGY = "yolo26_pose_head"
TASK_CLASSES = {
    "presence": ("absent", "present"),
    "awake": ("asleep", "awake"),
    "pacifier": ("no", "yes"),
}
POSITIVE_CLASS = {task: classes[1] for task, classes in TASK_CLASSES.items()}
DEPLOYMENT_REQUIREMENTS = {
    "presence": {
        "selective_accuracy": 0.97,
        "coverage": 0.80,
        "positive_precision": 0.95,
        "negative_precision": 0.95,
        "positive_recall": 0.80,
        "negative_recall": 0.80,
    },
    "awake": {
        "selective_accuracy": 0.95,
        "coverage": 0.50,
        "positive_precision": 0.90,
        "negative_precision": 0.90,
        "positive_recall": 0.50,
        "negative_recall": 0.50,
    },
    "pacifier": {
        "selective_accuracy": 0.95,
        "coverage": 0.50,
        "positive_precision": 0.90,
        "negative_precision": 0.90,
        "positive_recall": 0.50,
        "negative_recall": 0.50,
    },
}
INDEX_FIELDS = (
    "task",
    "sample_id",
    "frame_id",
    "captured_at",
    "location_id",
    "split",
    "target",
    "class_name",
    "crop_name",
    "crop_x0",
    "crop_y0",
    "crop_x1",
    "crop_y1",
    "crop_path",
)


@dataclass(frozen=True, slots=True)
class YoloTrainingConfig:
    base_model: str = "yolo26n-cls.pt"
    image_size: int = 320
    batch_size: int = 8
    epochs: int = 40
    patience: int = 8
    learning_rate: float = 0.001
    device: str = "mps"
    seed: int = 20260729
    workers: int = 0


@dataclass(frozen=True, slots=True)
class PoseHeadConfig:
    image_size: int = 640
    batch_size: int = 16
    device: str = "mps"
    detection_confidence: float = 0.2
    nose_confidence: float = 0.45
    head_keypoint_confidence: float = 0.3


def _disable_ultralytics_integrations() -> None:
    from ultralytics.utils import SETTINGS

    dict.update(
        SETTINGS,
        {
            "sync": False,
            "clearml": False,
            "comet": False,
            "dvc": False,
            "hub": False,
            "mlflow": False,
            "neptune": False,
            "raytune": False,
            "tensorboard": False,
            "wandb": False,
        },
    )


def _safe_generated_directory(path: Path, marker: str, *, overwrite: bool) -> Path:
    resolved = path.resolve()
    if resolved == Path(resolved.anchor) or len(resolved.parts) < 4:
        raise ValueError(f"refusing to use broad generated directory: {resolved}")
    marker_path = resolved / marker
    if resolved.exists() and any(resolved.iterdir()):
        if not overwrite:
            raise FileExistsError(f"{resolved} is not empty; pass overwrite=True to rebuild it")
        if not marker_path.is_file():
            raise ValueError(f"refusing to replace unmarked generated directory: {resolved}")
        shutil.rmtree(resolved)
    resolved.mkdir(parents=True, exist_ok=True)
    marker_path.write_text("generated by baby-monitor-edge\n", encoding="utf-8")
    return resolved


def _safe_frame_path(frames_dir: Path, relative_path: str) -> Path:
    root = frames_dir.resolve()
    candidate = (root / relative_path).resolve()
    if not candidate.is_relative_to(root):
        raise ValueError(f"frame path escapes the private frames directory: {relative_path}")
    if not candidate.is_file():
        raise FileNotFoundError(candidate)
    return candidate


def _crop_key(example: FrameExample, variant: str = "roi") -> str:
    digest = hashlib.sha256(example.sample_id.encode()).hexdigest()[:24]
    suffix = "" if variant == "roi" else f"-{variant}"
    return f"{example.frame_id}-{digest}{suffix}.jpg"


def _materialize_crop(
    example: FrameExample,
    frames_dir: Path,
    crop_path: Path,
    image_size: int,
    *,
    rect: tuple[float, float, float, float] | None = None,
    fit: bool = False,
) -> None:
    if crop_path.is_file():
        return
    source = _safe_frame_path(frames_dir, example.relative_path)
    with Image.open(source) as raw:
        image = ImageOps.exif_transpose(raw).convert("RGB")
        width, height = image.size
        x0, y0, x1, y1 = rect or (
            example.crop_x0,
            example.crop_y0,
            example.crop_x1,
            example.crop_y1,
        )
        box = (round(x0 * width), round(y0 * height), round(x1 * width), round(y1 * height))
        cropped = image.crop(box)
        if fit:
            prepared = ImageOps.fit(
                cropped,
                (image_size, image_size),
                method=Image.Resampling.LANCZOS,
            )
        else:
            prepared = ImageOps.pad(
                cropped,
                (image_size, image_size),
                method=Image.Resampling.LANCZOS,
                color=(114, 114, 114),
                centering=(0.5, 0.5),
            )
        crop_path.parent.mkdir(parents=True, exist_ok=True)
        prepared.save(crop_path, format="JPEG", quality=92, optimize=True)


def _select_pose_head_rect(
    *,
    boxes: list[list[float]],
    box_confidences: list[float],
    keypoints: list[list[list[float]]],
    keypoint_confidences: list[list[float]],
    roi: tuple[float, float, float, float],
    width: int,
    height: int,
    config: PoseHeadConfig,
) -> tuple[float, float, float, float] | None:
    """Select a small likely-baby pose inside an ROI and return a square head crop."""

    x0, y0, x1, y1 = roi
    candidates: list[tuple[float, list[float], list[list[float]], list[float]]] = []
    for box, confidence, points, point_confidences in zip(
        boxes,
        box_confidences,
        keypoints,
        keypoint_confidences,
        strict=True,
    ):
        nose_x, nose_y = points[0]
        nose_confidence = point_confidences[0]
        if (
            confidence < config.detection_confidence
            or nose_confidence < config.nose_confidence
            or not (x0 <= nose_x <= x1 and y0 <= nose_y <= y1)
        ):
            continue
        area = max((box[2] - box[0]) * (box[3] - box[1]), 1e-5)
        baby_preference = confidence * nose_confidence / math.sqrt(area)
        candidates.append((baby_preference, box, points, point_confidences))
    if not candidates:
        return None
    _, box, points, point_confidences = max(candidates, key=lambda item: item[0])
    visible_head = [
        point
        for point, confidence in zip(
            points[:5],
            point_confidences[:5],
            strict=True,
        )
        if confidence >= config.head_keypoint_confidence
    ]
    if not visible_head:
        return None
    head_x = [point[0] * width for point in visible_head]
    head_y = [point[1] * height for point in visible_head]
    span = max(max(head_x) - min(head_x), max(head_y) - min(head_y))
    box_width = (box[2] - box[0]) * width
    box_height = (box[3] - box[1]) * height
    side = max(2.2 * span, 0.22 * box_width, 0.16 * box_height, 96)
    side = min(side, 0.5 * min(width, height))
    nose_x = points[0][0] * width
    nose_y = points[0][1] * height
    left = max(0.0, min(width - side, nose_x - side / 2))
    top = max(0.0, min(height - side, nose_y + 0.12 * side - side / 2))
    return (left / width, top / height, (left + side) / width, (top + side) / height)


def _locate_pose_heads(
    examples: tuple[FrameExample, ...],
    frames_dir: Path,
    model_path: Path,
    *,
    config: PoseHeadConfig,
) -> dict[str, tuple[float, float, float, float] | None]:
    from ultralytics import YOLO

    _disable_ultralytics_integrations()
    if config.image_size < 320 or config.batch_size < 1:
        raise ValueError("pose-head image and batch sizes are invalid")
    for value in (
        config.detection_confidence,
        config.nose_confidence,
        config.head_keypoint_confidence,
    ):
        if not 0 <= value <= 1:
            raise ValueError("pose-head confidence thresholds must be within [0, 1]")
    root = frames_dir.resolve()
    grouped: dict[str, list[FrameExample]] = defaultdict(list)
    for example in examples:
        grouped[example.relative_path].append(example)
    model = YOLO(str(model_path.resolve()))
    located: dict[str, tuple[float, float, float, float] | None] = {}
    items = sorted(grouped.items())
    for start in range(0, len(items), config.batch_size):
        batch = items[start : start + config.batch_size]
        paths = [str(_safe_frame_path(root, relative_path)) for relative_path, _ in batch]
        results = model.predict(
            paths,
            imgsz=config.image_size,
            device=config.device,
            batch=config.batch_size,
            conf=min(0.15, config.detection_confidence),
            verbose=False,
        )
        for (_, frame_examples), result in zip(batch, results, strict=True):
            if result.boxes is None or result.keypoints is None or result.keypoints.conf is None:
                for example in frame_examples:
                    located[example.sample_id] = None
                continue
            height, width = result.orig_shape
            boxes = result.boxes.xyxyn.detach().cpu().tolist()
            box_confidences = result.boxes.conf.detach().cpu().tolist()
            keypoints = result.keypoints.xyn.detach().cpu().tolist()
            keypoint_confidences = result.keypoints.conf.detach().cpu().tolist()
            for example in frame_examples:
                located[example.sample_id] = _select_pose_head_rect(
                    boxes=boxes,
                    box_confidences=box_confidences,
                    keypoints=keypoints,
                    keypoint_confidences=keypoint_confidences,
                    roi=(
                        example.crop_x0,
                        example.crop_y0,
                        example.crop_x1,
                        example.crop_y1,
                    ),
                    width=width,
                    height=height,
                    config=config,
                )
    return located


def _deterministic_order(examples: list[FrameExample], *parts: object) -> list[FrameExample]:
    prefix = ":".join(str(part) for part in parts)
    return sorted(
        examples,
        key=lambda example: hashlib.sha256(f"{prefix}:{example.sample_id}".encode()).hexdigest(),
    )


def _temporal_consensus_ids(
    examples: tuple[FrameExample, ...],
    task: str,
    *,
    maximum_gap_seconds: float = 10 * 60,
) -> set[str]:
    """Retain detail labels backed by a nearby observation with the same value."""

    grouped: dict[tuple[str, str], list[FrameExample]] = defaultdict(list)
    for example in examples:
        if example.split == "train" and example.mask(task):
            grouped[(example.location_id, example.crop_name)].append(example)
    accepted: set[str] = set()
    for group in grouped.values():
        ordered = sorted(group, key=lambda item: (item.captured_at, item.frame_id))
        timestamps = [datetime.fromisoformat(item.captured_at.replace("Z", "+00:00")) for item in ordered]
        for index, example in enumerate(ordered):
            for neighbor_index in (index - 1, index + 1):
                if not 0 <= neighbor_index < len(ordered):
                    continue
                neighbor = ordered[neighbor_index]
                gap = abs((timestamps[index] - timestamps[neighbor_index]).total_seconds())
                if gap <= maximum_gap_seconds and example.target(task) == neighbor.target(task):
                    accepted.add(example.sample_id)
                    break
    return accepted


def _balanced_training_rows(
    examples: list[FrameExample],
    task: str,
    *,
    seed: int,
    max_minority_repeats: int,
) -> list[tuple[FrameExample, int]]:
    by_target = {
        target: _deterministic_order(
            [example for example in examples if example.target(task) == target],
            seed,
            task,
            target,
        )
        for target in (0, 1)
    }
    if not by_target[0] or not by_target[1]:
        raise ValueError(f"{task} training split must contain both classes")
    desired = min(
        max(len(by_target[0]), len(by_target[1])),
        min(len(by_target[0]), len(by_target[1])) * max_minority_repeats,
    )
    rows: list[tuple[FrameExample, int]] = []
    for _target, candidates in by_target.items():
        selected = candidates[:desired]
        for index in range(desired):
            rows.append((selected[index % len(selected)], index // len(selected)))
    return sorted(
        rows,
        key=lambda item: hashlib.sha256(f"{seed}:{task}:{item[0].sample_id}:{item[1]}".encode()).hexdigest(),
    )


def _surface_for_crop(examples: list[FrameExample]) -> str:
    positive = [example for example in examples if example.presence_target]
    if any(example.sleep_surface == "family_bed" for example in positive):
        return "family_bed"
    if any(example.sleep_surface == "crib" or example.in_crib is True for example in positive):
        return "crib"
    if any(example.sleep_surface == "other" or example.in_crib is False for example in positive):
        return "other"
    return "unknown"


def _roi_profiles(examples: tuple[FrameExample, ...]) -> dict[str, list[dict[str, Any]]]:
    grouped: dict[tuple[str, str, float, float, float, float], list[FrameExample]] = defaultdict(list)
    for example in examples:
        grouped[
            (
                example.location_id,
                example.crop_name,
                example.crop_x0,
                example.crop_y0,
                example.crop_x1,
                example.crop_y1,
            )
        ].append(example)
    profiles: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for (location, name, x0, y0, x1, y1), crop_examples in sorted(grouped.items()):
        profiles[location].append(
            {
                "name": name,
                "rect": [x0, y0, x1, y1],
                "surface": _surface_for_crop(crop_examples),
            }
        )
    return dict(profiles)


def _cached_crop(
    example: FrameExample,
    cache: dict[tuple[str, str], Path],
    crops_dir: Path,
    frames_dir: Path,
    image_size: int,
    *,
    variant: str = "roi",
    rect: tuple[float, float, float, float] | None = None,
) -> Path:
    key = (example.sample_id, variant)
    path = cache.get(key)
    if path is None:
        path = crops_dir / _crop_key(example, variant)
        _materialize_crop(
            example,
            frames_dir,
            path,
            image_size,
            rect=rect,
            fit=variant == "head",
        )
        cache[key] = path
    return path


def prepare_yolo_dataset(
    manifest_path: Path,
    frames_dir: Path,
    output_dir: Path,
    *,
    image_size: int = 320,
    seed: int = 20260729,
    max_minority_repeats: int = 6,
    temporal_consensus: bool = True,
    pose_model_path: Path | None = None,
    pose_config: PoseHeadConfig | None = None,
    overwrite: bool = False,
) -> dict[str, Any]:
    """Materialize privacy-local, leakage-safe YOLO classification datasets."""

    if image_size < 96:
        raise ValueError("YOLO image size must be at least 96 pixels")
    if max_minority_repeats < 1:
        raise ValueError("max_minority_repeats must be positive")
    output = _safe_generated_directory(output_dir, YOLO_DATASET_MARKER, overwrite=overwrite)
    frames_root = frames_dir.resolve()
    examples = read_manifest(manifest_path)
    consensus = {task: _temporal_consensus_ids(examples, task) for task in ("awake", "pacifier")}
    pose_heads: dict[str, tuple[float, float, float, float] | None] | None = None
    resolved_pose_model: Path | None = None
    pose_config = pose_config or PoseHeadConfig()
    if pose_model_path is not None:
        resolved_pose_model = pose_model_path.resolve()
        if not resolved_pose_model.is_file():
            raise FileNotFoundError(resolved_pose_model)
        detail_examples = tuple(
            {
                example.sample_id: example for example in examples if example.mask("awake") or example.mask("pacifier")
            }.values()
        )
        pose_heads = _locate_pose_heads(
            detail_examples,
            frames_root,
            resolved_pose_model,
            config=pose_config,
        )
        support_path = output / "support" / "head_pose.pt"
        support_path.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(resolved_pose_model, support_path)
    crops_dir = output / "crops"
    index_rows: list[dict[str, Any]] = []
    summary: dict[str, Any] = {
        "manifest_sha256": hashlib.sha256(manifest_path.read_bytes()).hexdigest(),
        "image_size": image_size,
        "seed": seed,
        "temporal_consensus": temporal_consensus,
        "roi_profiles": _roi_profiles(examples),
        "tasks": {},
    }
    if resolved_pose_model is not None:
        summary["detail_crop"] = {
            "strategy": POSE_DETAIL_STRATEGY,
            "image_size": pose_config.image_size,
            "detection_confidence": pose_config.detection_confidence,
            "nose_confidence": pose_config.nose_confidence,
            "head_keypoint_confidence": pose_config.head_keypoint_confidence,
            "support_model": {
                "path": "support/head_pose.pt",
                "bytes": resolved_pose_model.stat().st_size,
                "sha256": hashlib.sha256(resolved_pose_model.read_bytes()).hexdigest(),
            },
        }

    for task in TASKS:
        eligible = [example for example in examples if example.mask(task)]
        pose_detection: dict[str, dict[str, dict[str, Any]]] | None = None
        excluded_pose_misses = 0
        if pose_heads is not None and task in {"awake", "pacifier"}:
            pose_detection = defaultdict(dict)
            for split in ("train", "validation", "test"):
                split_examples = [example for example in eligible if example.split == split]
                for location in sorted({example.location_id for example in split_examples}):
                    location_examples = [example for example in split_examples if example.location_id == location]
                    detected = [
                        example for example in location_examples if pose_heads.get(example.sample_id) is not None
                    ]
                    eligible_by_target = Counter(example.target(task) for example in location_examples)
                    detected_by_target = Counter(example.target(task) for example in detected)
                    pose_detection[split][location] = {
                        "eligible": len(location_examples),
                        "detected": len(detected),
                        "coverage": len(detected) / len(location_examples),
                        "eligible_negative": eligible_by_target[0],
                        "eligible_positive": eligible_by_target[1],
                        "detected_negative": detected_by_target[0],
                        "detected_positive": detected_by_target[1],
                    }
            excluded_pose_misses = sum(pose_heads.get(example.sample_id) is None for example in eligible)
            eligible = [example for example in eligible if pose_heads.get(example.sample_id) is not None]
        training = [example for example in eligible if example.split == "train"]
        excluded_inconsistent = 0
        if temporal_consensus and task in consensus:
            accepted = consensus[task]
            excluded_inconsistent = sum(example.sample_id not in accepted for example in training)
            training = [example for example in training if example.sample_id in accepted]
        train_rows = _balanced_training_rows(
            training,
            task,
            seed=seed,
            max_minority_repeats=max_minority_repeats,
        )
        task_summary: dict[str, Any] = {
            "excluded_inconsistent_train_labels": excluded_inconsistent,
            "excluded_pose_misses": excluded_pose_misses,
            "splits": {},
        }
        if pose_detection is not None:
            task_summary["pose_detection"] = pose_detection
        materialized: dict[tuple[str, str], Path] = {}

        for manifest_split, yolo_split in (
            ("train", "train"),
            ("validation", "val"),
            ("test", "test"),
        ):
            if manifest_split == "train":
                rows = train_rows
            else:
                rows = [(example, 0) for example in eligible if example.split == manifest_split]
            counts: Counter[str] = Counter()
            for example, repeat in rows:
                target = example.target(task)
                class_name = TASK_CLASSES[task][target]
                head_rect = (
                    pose_heads.get(example.sample_id)
                    if pose_heads is not None and task in {"awake", "pacifier"}
                    else None
                )
                variant = "head" if head_rect is not None else "roi"
                crop_path = _cached_crop(
                    example,
                    materialized,
                    crops_dir,
                    frames_root,
                    image_size,
                    variant=variant,
                    rect=head_rect,
                )
                alias = f"{Path(crop_path).stem}__{repeat}.jpg"
                link = output / task / yolo_split / class_name / alias
                link.parent.mkdir(parents=True, exist_ok=True)
                relative_target = os.path.relpath(crop_path, link.parent)
                link.symlink_to(relative_target)
                counts[class_name] += 1
                if repeat == 0:
                    index_rows.append(
                        {
                            "task": task,
                            "sample_id": example.sample_id,
                            "frame_id": example.frame_id,
                            "captured_at": example.captured_at,
                            "location_id": example.location_id,
                            "split": manifest_split,
                            "target": target,
                            "class_name": class_name,
                            "crop_name": example.crop_name,
                            "crop_x0": example.crop_x0,
                            "crop_y0": example.crop_y0,
                            "crop_x1": example.crop_x1,
                            "crop_y1": example.crop_y1,
                            "crop_path": str(crop_path.relative_to(output)),
                        }
                    )
            task_summary["splits"][manifest_split] = {
                "examples": len(rows),
                "classes": dict(sorted(counts.items())),
            }
        summary["tasks"][task] = task_summary

    with (output / "index.csv").open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=INDEX_FIELDS)
        writer.writeheader()
        writer.writerows(index_rows)
    summary["unique_crops"] = len({row["crop_path"] for row in index_rows})
    (output / "summary.json").write_text(
        json.dumps(summary, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return summary


def train_yolo_classifiers(
    dataset_dir: Path,
    output_dir: Path,
    *,
    config: YoloTrainingConfig | None = None,
    overwrite: bool = False,
    resume: bool = False,
) -> dict[str, Any]:
    """Fine-tune one compact pretrained YOLO classifier per conditional output."""

    from ultralytics import YOLO
    from ultralytics import __version__ as ultralytics_version

    _disable_ultralytics_integrations()

    config = config or YoloTrainingConfig()
    dataset = dataset_dir.resolve()
    if not (dataset / YOLO_DATASET_MARKER).is_file():
        raise ValueError(f"{dataset} is not a Baby Monitor YOLO dataset")
    if overwrite and resume:
        raise ValueError("overwrite and resume cannot be used together")
    if resume:
        output = output_dir.resolve()
        if not (output / YOLO_ARTIFACT_MARKER).is_file():
            raise ValueError(f"{output} is not a resumable Baby Monitor YOLO artifact")
    else:
        output = _safe_generated_directory(
            output_dir,
            YOLO_ARTIFACT_MARKER,
            overwrite=overwrite,
        )
    plan = {
        "config": asdict(config),
        "dataset_summary": json.loads((dataset / "summary.json").read_text(encoding="utf-8")),
    }
    plan_path = output / "training-plan.json"
    if resume:
        try:
            existing_plan = json.loads(plan_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            raise ValueError(f"{output} has no valid resumable training plan") from exc
        if existing_plan != plan:
            raise ValueError("resume configuration or dataset does not match the original run")
    else:
        plan_path.write_text(
            json.dumps(plan, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
    models_dir = output / "models"
    models_dir.mkdir(parents=True, exist_ok=True)
    support_models: dict[str, Any] = {}
    detail_crop = plan["dataset_summary"].get("detail_crop")
    if isinstance(detail_crop, dict):
        source_metadata = detail_crop.get("support_model")
        if not isinstance(source_metadata, dict) or not isinstance(
            source_metadata.get("path"),
            str,
        ):
            raise ValueError("pose-head dataset has invalid support model metadata")
        source = (dataset / source_metadata["path"]).resolve()
        if not source.is_relative_to(dataset) or not source.is_file():
            raise ValueError("pose-head dataset support model is unavailable")
        target = models_dir / "head_pose.pt"
        if not target.is_file():
            shutil.copy2(source, target)
        digest = hashlib.sha256(target.read_bytes()).hexdigest()
        if digest != source_metadata.get("sha256"):
            raise ValueError("pose-head dataset support model integrity check failed")
        support_models["detail_pose"] = {
            "path": str(target.relative_to(output)),
            "bytes": target.stat().st_size,
            "sha256": digest,
        }
    trained: dict[str, Any] = {}
    for task in TASKS:
        target = models_dir / f"{task}.pt"
        if resume and target.is_file():
            trained[task] = {
                "path": str(target.relative_to(output)),
                "bytes": target.stat().st_size,
                "sha256": hashlib.sha256(target.read_bytes()).hexdigest(),
            }
            continue
        model = YOLO(config.base_model)
        model.train(
            data=str(dataset / task),
            epochs=config.epochs,
            imgsz=config.image_size,
            batch=config.batch_size,
            device=config.device,
            workers=config.workers,
            patience=config.patience,
            lr0=config.learning_rate,
            optimizer="AdamW",
            cos_lr=True,
            dropout=0.1,
            auto_augment="randaugment",
            erasing=0.1,
            scale=0.1,
            amp=False,
            deterministic=True,
            seed=config.seed,
            project=str(output / "runs"),
            name=task,
            exist_ok=True,
            plots=False,
            verbose=True,
        )
        best = output / "runs" / task / "weights" / "best.pt"
        if not best.is_file():
            raise RuntimeError(f"Ultralytics did not produce {best}")
        shutil.copy2(best, target)
        trained[task] = {
            "path": str(target.relative_to(output)),
            "bytes": target.stat().st_size,
            "sha256": hashlib.sha256(target.read_bytes()).hexdigest(),
        }
    result = {
        "created_at": datetime.now(UTC).isoformat(),
        "ultralytics_version": ultralytics_version,
        **plan,
        "models": trained,
        "support_models": support_models,
    }
    (output / "training.json").write_text(
        json.dumps(result, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return result


def _prediction_scores(
    model_path: Path,
    rows: list[dict[str, str]],
    dataset_dir: Path,
    task: str,
    *,
    image_size: int,
    device: str,
    batch_size: int,
) -> list[dict[str, Any]]:
    from ultralytics import YOLO

    _disable_ultralytics_integrations()
    model = YOLO(str(model_path))
    predictions: list[dict[str, Any]] = []
    # Ultralytics treats a Python list of images as one in-memory batch even
    # when ``batch=`` is supplied. Chunk explicitly so held-out evaluation does
    # not attempt to load thousands of private crops into RAM or MPS at once.
    for start in range(0, len(rows), batch_size):
        batch_rows = rows[start : start + batch_size]
        paths = [str(dataset_dir / row["crop_path"]) for row in batch_rows]
        results = model.predict(
            paths,
            imgsz=image_size,
            device=device,
            batch=batch_size,
            verbose=False,
        )
        for row, result in zip(batch_rows, results, strict=True):
            if result.probs is None:
                raise RuntimeError(f"{model_path} did not return classification probabilities")
            positive_index = next(index for index, name in result.names.items() if name == POSITIVE_CLASS[task])
            score = float(result.probs.data[positive_index].detach().cpu())
            predictions.append(
                {
                    **row,
                    "target": int(row["target"]),
                    "score": score,
                }
            )
    return predictions


def _runtime_rows(rows: list[dict[str, Any]], task: str) -> list[dict[str, Any]]:
    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for row in rows:
        grouped[row["frame_id"]].append(row)
    runtime: list[dict[str, Any]] = []
    for frame_rows in grouped.values():
        if task == "presence":
            winner = max(frame_rows, key=lambda row: row["score"])
            runtime.append(
                {
                    **winner,
                    "target": max(row["target"] for row in frame_rows),
                    "score": max(row["score"] for row in frame_rows),
                }
            )
        else:
            runtime.append(frame_rows[0])
    return runtime


def _metrics_by_location(
    rows: list[dict[str, Any]],
    threshold: float,
) -> dict[str, Any]:
    report: dict[str, Any] = {}
    for location in ("overall", *sorted({row["location_id"] for row in rows})):
        subset = rows if location == "overall" else [row for row in rows if row["location_id"] == location]
        truth = np.asarray([row["target"] for row in subset], dtype=np.int8)
        scores = np.asarray([row["score"] for row in subset], dtype=np.float32)
        report[location] = binary_metrics(truth, scores, threshold)
    return report


def _selective_metrics_by_location(
    rows: list[dict[str, Any]],
    thresholds: dict[str, dict[str, float]],
) -> dict[str, Any]:
    report: dict[str, Any] = {}
    for location in ("overall", *sorted({row["location_id"] for row in rows})):
        subset = rows if location == "overall" else [row for row in rows if row["location_id"] == location]
        selected = thresholds.get(location, thresholds["overall"])
        report[location] = selective_binary_metrics(
            np.asarray([row["target"] for row in subset], dtype=np.int8),
            np.asarray([row["score"] for row in subset], dtype=np.float32),
            selected["negative"],
            selected["positive"],
        )
    return report


def _include_pose_abstentions(
    metrics_by_location: dict[str, Any],
    task_summary: dict[str, Any],
    split: str,
) -> dict[str, Any]:
    detection = task_summary.get("pose_detection")
    if not isinstance(detection, dict) or not isinstance(detection.get(split), dict):
        return metrics_by_location
    by_location = detection[split]
    adjusted: dict[str, Any] = {}
    for location, metrics in metrics_by_location.items():
        if location == "overall":
            slices = list(by_location.values())
        else:
            raw = by_location.get(location)
            if not isinstance(raw, dict):
                raise ValueError(f"pose detection summary is missing {split}/{location}")
            slices = [raw]
        eligible = sum(int(item["eligible"]) for item in slices)
        detected = sum(int(item["detected"]) for item in slices)
        eligible_positive = sum(int(item["eligible_positive"]) for item in slices)
        eligible_negative = sum(int(item["eligible_negative"]) for item in slices)
        if int(metrics["samples"]) != detected:
            raise ValueError(f"pose detection summary does not match {task_summary=}")
        decisions = int(metrics["decisions"])
        item = dict(metrics)
        item.update(
            {
                "samples": eligible,
                "positive": eligible_positive,
                "negative": eligible_negative,
                "abstained": eligible - decisions,
                "coverage": decisions / eligible,
                "localizer_coverage": detected / eligible,
                "classifier_coverage": decisions / detected if detected else 0.0,
                "positive_recall": (int(metrics["true_positive"]) / eligible_positive if eligible_positive else None),
                "negative_recall": (int(metrics["true_negative"]) / eligible_negative if eligible_negative else None),
            }
        )
        adjusted[location] = item
    return adjusted


def _calibrate_by_location(rows: list[dict[str, Any]]) -> tuple[dict[str, dict[str, float]], dict[str, Any]]:
    thresholds: dict[str, dict[str, float]] = {}
    metrics: dict[str, Any] = {}
    for location in ("overall", *sorted({row["location_id"] for row in rows})):
        subset = rows if location == "overall" else [row for row in rows if row["location_id"] == location]
        negative, positive, selected = select_abstention_thresholds(
            np.asarray([row["target"] for row in subset], dtype=np.int8),
            np.asarray([row["score"] for row in subset], dtype=np.float32),
        )
        thresholds[location] = {"negative": negative, "positive": positive}
        metrics[location] = selected
    return thresholds, metrics


def _deployment_gate(selective_test: dict[str, Any]) -> dict[str, Any]:
    tasks: dict[str, Any] = {}
    for task, requirements in DEPLOYMENT_REQUIREMENTS.items():
        locations: dict[str, Any] = {}
        for location, metrics in selective_test[task].items():
            checks = {
                metric: metrics.get(metric) is not None and float(metrics[metric]) >= minimum
                for metric, minimum in requirements.items()
            }
            locations[location] = {
                "passed": all(checks.values()),
                "checks": checks,
                "requirements": requirements,
            }
        tasks[task] = {
            "passed": all(item["passed"] for item in locations.values()),
            "locations": locations,
        }
    return {
        "automated_metrics_passed": all(item["passed"] for item in tasks.values()),
        "manual_review_required": True,
        "tasks": tasks,
    }


def _markdown_report(report: dict[str, Any]) -> str:
    def percentage(value: float | None) -> str:
        return "n/a" if value is None else f"{value:.1%}"

    detail_crop = report["metadata"].get("detail_crop")
    architecture = (
        "- Architecture: YOLO26 pose head localization plus three YOLO26 nano classifiers."
        if isinstance(detail_crop, dict)
        else "- Architecture: three YOLO26 nano classifiers fine-tuned from ImageNet weights."
    )
    lines = [
        "# Baby Monitor YOLO report",
        "",
        architecture,
        "- Split: newest days per home are test-only; no location/day crosses splits.",
        "- Labels: historical Gemini labels are weak supervision, not clinical ground truth.",
        f"- Runtime version: `{report['metadata']['version']}`.",
        "",
        "## Held-out test agreement",
        "",
        (
            "| Task | Location | Samples | Balanced accuracy | Selective accuracy | Coverage | "
            "Positive precision | Negative precision | Positive recall | Negative recall |"
        ),
        "| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for task in TASKS:
        for location, metrics in report["test"][task].items():
            selective = report["selective_test"][task][location]
            lines.append(
                f"| {task} | {location} | {selective['samples']} | "
                f"{percentage(metrics['balanced_accuracy'])} | "
                f"{percentage(selective['selective_accuracy'])} | "
                f"{percentage(selective['coverage'])} | "
                f"{percentage(selective['positive_precision'])} | "
                f"{percentage(selective['negative_precision'])} | "
                f"{percentage(selective['positive_recall'])} | "
                f"{percentage(selective['negative_recall'])} |"
            )
    lines.extend(
        (
            "",
            "Single and high-confidence abstention thresholds were selected on validation days only. "
            "Test days were not used for training or calibration.",
            "",
            (
                f"Decisive test disagreements queued for manual review: "
                f"**{report['audit']['high_confidence_disagreements']}**."
            ),
            "",
            (
                "**Automated deployment metrics: PASSED.**"
                if report["deployment_gate"]["automated_metrics_passed"]
                else "**Automated deployment metrics: NOT PASSED.**"
            ),
            "Manual review is still required because the source labels are weak supervision.",
            "",
        )
    )
    return "\n".join(lines)


def evaluate_yolo_classifiers(
    dataset_dir: Path,
    artifact_dir: Path,
    *,
    device: str = "cpu",
    batch_size: int = 4,
) -> dict[str, Any]:
    dataset = dataset_dir.resolve()
    artifacts = artifact_dir.resolve()
    training = json.loads((artifacts / "training.json").read_text(encoding="utf-8"))
    with (dataset / "index.csv").open(newline="", encoding="utf-8") as handle:
        index = list(csv.DictReader(handle))
    image_size = int(training["config"]["image_size"])
    thresholds: dict[str, float] = {}
    selective_thresholds: dict[str, dict[str, dict[str, float]]] = {}
    validation: dict[str, Any] = {}
    test: dict[str, Any] = {}
    selective_validation: dict[str, Any] = {}
    selective_test: dict[str, Any] = {}
    prediction_rows: list[dict[str, Any]] = []
    high_confidence_errors: list[dict[str, Any]] = []
    for task in TASKS:
        task_rows = [row for row in index if row["task"] == task and row["split"] != "train"]
        scored = _prediction_scores(
            artifacts / training["models"][task]["path"],
            task_rows,
            dataset,
            task,
            image_size=image_size,
            device=device,
            batch_size=batch_size,
        )
        prediction_rows.extend(scored)
        validation_rows = _runtime_rows(
            [row for row in scored if row["split"] == "validation"],
            task,
        )
        test_rows = _runtime_rows(
            [row for row in scored if row["split"] == "test"],
            task,
        )
        threshold, selected = select_threshold(
            np.asarray([row["target"] for row in validation_rows], dtype=np.int8),
            np.asarray([row["score"] for row in validation_rows], dtype=np.float32),
        )
        thresholds[task] = threshold
        task_selective_thresholds, task_selective_validation = _calibrate_by_location(validation_rows)
        selective_thresholds[task] = task_selective_thresholds
        validation[task] = {
            "selected_threshold": threshold,
            "overall": selected,
            **{
                key: value
                for key, value in _metrics_by_location(validation_rows, threshold).items()
                if key != "overall"
            },
        }
        test[task] = _metrics_by_location(test_rows, threshold)
        selective_validation[task] = task_selective_validation
        selective_test[task] = _selective_metrics_by_location(
            test_rows,
            task_selective_thresholds,
        )
        task_summary = training["dataset_summary"]["tasks"][task]
        selective_validation[task] = _include_pose_abstentions(
            selective_validation[task],
            task_summary,
            "validation",
        )
        selective_test[task] = _include_pose_abstentions(
            selective_test[task],
            task_summary,
            "test",
        )
        for row in test_rows:
            bounds = task_selective_thresholds.get(
                row["location_id"],
                task_selective_thresholds["overall"],
            )
            decision = 0 if row["score"] <= bounds["negative"] else 1 if row["score"] >= bounds["positive"] else None
            if decision is not None and decision != row["target"]:
                high_confidence_errors.append(
                    {
                        **row,
                        "decision": decision,
                        "negative_threshold": bounds["negative"],
                        "positive_threshold": bounds["positive"],
                    }
                )

    with (artifacts / "predictions.csv").open("w", newline="", encoding="utf-8") as handle:
        fields = [*INDEX_FIELDS, "score"]
        writer = csv.DictWriter(handle, fieldnames=fields, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(prediction_rows)
    with (artifacts / "high_confidence_errors.csv").open(
        "w",
        newline="",
        encoding="utf-8",
    ) as handle:
        fields = [
            *INDEX_FIELDS,
            "score",
            "decision",
            "negative_threshold",
            "positive_threshold",
        ]
        writer = csv.DictWriter(handle, fieldnames=fields, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(
            sorted(
                high_confidence_errors,
                key=lambda row: (row["task"], row["location_id"], -abs(row["score"] - 0.5)),
            )
        )
    fingerprint_payload = {
        "fingerprint_version": 1,
        "image_size": image_size,
        "models": {task: training["models"][task]["sha256"] for task in TASKS},
        "roi_profiles": training["dataset_summary"]["roi_profiles"],
        "thresholds": thresholds,
        "selective_thresholds": selective_thresholds,
    }
    detail_crop = training["dataset_summary"].get("detail_crop")
    if isinstance(detail_crop, dict):
        support_model = training.get("support_models", {}).get("detail_pose")
        if not isinstance(support_model, dict):
            raise ValueError("pose-head training metadata has no support model")
        fingerprint_payload["detail_crop"] = {
            **{key: value for key, value in detail_crop.items() if key != "support_model"},
            "model": support_model,
        }
    model_fingerprint = hashlib.sha256(
        json.dumps(fingerprint_payload, sort_keys=True, separators=(",", ":")).encode()
    ).hexdigest()[:12]
    metadata = {
        "format": "Ultralytics YOLO26 classification",
        "fingerprint_version": 1,
        "version": f"baby-monitor-yolo-{model_fingerprint}",
        "image_size": image_size,
        "tasks": {
            task: {
                **training["models"][task],
                "positive_class": POSITIVE_CLASS[task],
                "threshold": thresholds[task],
                "thresholds": selective_thresholds[task],
            }
            for task in TASKS
        },
        "roi_profiles": training["dataset_summary"]["roi_profiles"],
    }
    if "detail_crop" in fingerprint_payload:
        metadata["detail_crop"] = fingerprint_payload["detail_crop"]
    report = {
        **training,
        "thresholds": thresholds,
        "selective_thresholds": selective_thresholds,
        "validation": validation,
        "test": test,
        "selective_validation": selective_validation,
        "selective_test": selective_test,
        "deployment_gate": _deployment_gate(selective_test),
        "metadata": metadata,
        "audit": {
            "high_confidence_disagreements": len(high_confidence_errors),
            "high_confidence_errors_csv": "high_confidence_errors.csv",
        },
    }
    (artifacts / "metadata.json").write_text(
        json.dumps(metadata, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    (artifacts / "report.json").write_text(
        json.dumps(report, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    (artifacts / "report.md").write_text(_markdown_report(report), encoding="utf-8")
    return report
